- name: Prerequisites
  hosts: master
  become: true
  tasks:

    - name: Install required packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

    - name: Check keyring directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '755'

    - name: Create temp directory
      ansible.builtin.file:
        path: /tmp/exjobb
        state: directory
        mode: '0755'

    - name: Download Kubernetes apt key
      ansible.builtin.get_url:
        url: 'https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key'
        dest: /tmp/exjobb/kubernetes_apt_key.key
        mode: '644'

    - name: Convert key to a compatible format
      ansible.builtin.command:
        cmd: >
          gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          /tmp/exjobb/kubernetes_apt_key.key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
          https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /
        filename: kubernetes
        state: present

    - name: Install containerd
      ansible.builtin.apt:
        name:
          - containerd

    - name: Configure containerd
      ansible.builtin.shell:
        cmd: >
          set -o pipefail &&
          containerd config default
          | sed 's/SystemdCgroup = false/SystemdCgroup = true/'
          | sed 's|sandbox_image = ".*"|sandbox_image =
          "registry.k8s.io/pause:3.10"|'
          | tee /etc/containerd/config.toml > /dev/null
      changed_when: false

    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted

    - name: Install Kubernetes packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: Hold Kubernetes packages
      ansible.builtin.dpkg_selections:
        name: '{{ item }}'
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Disable swap
      ansible.builtin.command:
        cmd: swapoff -a
      changed_when: false

    - name: Remove swap from fstab
      ansible.posix.mount:
        path: swap
        state: absent

    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
        reload: true
